webserver:
  hostname: "0.0.0.0"
  port: 5003

imageserver:
  crawler_upkeep: 10

logging:
  level: 'WARNING'

crawlers:
  - name: "Reddit"
    weight: 3
    config:
      subreddit: 'awww'
  - name: "Reddit"
    weight: 3
    config:
      subreddit: 'aww_gifs'
  - name: "Reddit"
    weight: 3
    config:
      subreddit: 'cats'
  - name: "Reddit"
    weight: 3
    config:
      subreddit: 'kittens'
  - name: "Pr0gramm"
    weight: 3
    config:
      tags: '!s:500 kadse -text'
      promoted: True
      
