name: "Test"

on: [push,pull_request]

jobs:
  test:
    name: Testing
    strategy:
      matrix:
        os: ['ubuntu-latest']
        pyhon: ['3.5', '3.6', '3.7', '3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.pyhon_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyhon }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools tox
      - name: Test nichtparasoup
        run: |
          python3 -m tox
      - name: "Test examples::nichtparasoup-imagecrawler-plugin"
        run: |
          python3 -m tox -c examples/nichtparasoup-imagecrawler-plugin/
      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: ${{ matrix.os }}_${{ matrix.pyhon }}
          yml: ./codecov.yml
