name: "Test"

on:
  push:
  pull_request:
  schedule:
    # this means: “At 23:42 on Friday.”
    - cron:  '42 23 * * 5'

jobs:
  test:
    name: Testing os:${{ matrix.os }} py:${{ matrix.pyhon }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        pyhon: ['3.5', '3.6', '3.7', '3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.pyhon_version }}
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyhon }}
      - name: Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools 'tox>3.10'
      - name: Test nichtparasoup
        run: python -m tox -e py3-coverageXML
      - name: "Test examples::nichtparasoup-imagecrawler-plugin"
        run:  python -m tox -c examples/nichtparasoup-imagecrawler-plugin/
      - name: Upload coverage to Codecov
        # see https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: tests
          name: od:${{ matrix.os }} py:${{ matrix.pyhon }}
          yml: ./codecov.yml
