## This is a config file for nichtprasoup (v2.3)
## This is an example file. For a better kickStart run: nichtparasoup server config --help

webserver:
  hostname: "0.0.0.0"
  port: 8080

imageserver:
  crawler_upkeep: 10

crawlers:
  - name: "Pr0gramm"
    config:
      tags: '!s:500 kadse -text'
      promoted: True
